### ISSUE TITLE
Can Meta's llama model be quantized to matmulfree?

### ISSUE THREAD

**Issue by impredicative** [ridgerchu/matmulfreellm#35]
Is it possible to quantize a matmul model such as Meta's Llama to matmulfree?

**Comment by ridgerchu** [comment]
Hi,
The matmul-free approach is more complex than simple quantization. It involves integrating a new attention mechanism and BitNet quantization. Due to this complexity, straightforward quantization is not feasible. Our experiments have shown that attempting to quantize the model to 1.58-bit results in significant performance degradation, rather than maintaining comparable performance levels.
